db-uri        = "postgres://howis@localhost:5432/shop_db"
db-schema     = "public"
db-anon-role  = "web_anon"
jwt-secret    = "super_secret_key_change_me_please_32chars"
server-port   = 3000
server-host   = "127.0.0.1"
